### ISSUE TITLE
Marathon Credentials

### ISSUE THREAD

**Issue by ndachel** [mesosphere/jenkins-marathon-plugin#19]
I am using this plugin with the DCOS Velocity service. My DCOS cluster requires authentication and therefore so does Marathon. Post deploy actions fail with : 

     [Marathon] Failed to update Marathon application:
     [Marathon] Unauthorized (http status: 401)

Should the plugin allow passing of credentials in the post deploy action?

**Comment by colin-msphere** [comment]
Token-based authentication was added in version 1.2.0. Username with Password authentication was added in version 1.2.1.

**Comment by alexraju** [comment]
@colin-msphere In Jenkins, I'm getting build error with the same Maration Unauthorized message.

[Marathon] Failed to update Marathon application:
[Marathon] Unauthorized (http status: 401)

I'm using plugin version 1.2.1.  In the credentials field, what information needs to be put to get authorized. 

Since I'm using Jenkin's 1.7, there is no username or password as the authentication is done using Google Oauth.

**Comment by ndachel** [comment]
@colin-msphere I updated to release 1.2.1 and this is available now. Thank you.
